# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10bWEL3tfJf48tTFGUZ1ZMDrWJoz6lxfY
"""

import pandas as pd
import numpy as np

df=pd.DataFrame(pd.read_csv('/content/sample_data/train (1).csv'))
df.head()

df.shape

df.isnull().sum()

drop_col=df.isnull().sum()[df.isnull().sum()>(35/100*df.shape[0])]
drop_col

drop_col.index

df.drop(drop_col.index,axis=1,inplace=True)
df.isnull().sum()

df.fillna(df.mean(), inplace=True)
df.isnull().sum()

"""Because Embarked contains string values,we see the details of that column seperately from others as strings does not have mean and all."""

df['Embarked'].describe()

"""For Embarked attribute,fill the NULL values with the most frequent value in the column."""

df['Embarked'].fillna('S',inplace=True)

df.isnull().sum()       ##now all the null have been filled

"""Correlation"""

df.corr()

df['FamilySize']=df['SibSp']+df['Parch']
df.drop(['SibSp','Parch'],axis=1,inplace=True)
df.corr()

"""FamilySize in the ship does not have much correlance with survival rate.

Let's check if whether the person was alone or not can affect the survival rate.

"""

df['Alone']=[0 if df['FamilySize'][i]>0 else 1 for i in df.index]
df.head()

df.groupby(['Alone'])['Survived'].mean()

"""If the person is alone he/she has less chance of surviving."""

df[['Alone','Fare']].corr()

"""If the person was not alone,the chance the ticket price is higher"""

df['Sex'] = [0 if df['Sex'][i] =='male' else 1 for i in df.index] #1 for female ,0 for male
df.groupby(['Sex'])['Survived'].mean()

"""It shows women were prioritized over men."""

df.groupby(['Embarked'])['Survived'].mean()

"""CONCLUSION

Female passengers were prioritized over men.

People with high class or rich people have higher survival rate than others.The hierarichy might have been followed while saving the passangers.

Passengers travelling with their family survival rate.

Passengers who bored the ship at Cherbourg,survived more in proportion then the others.
"""